version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql_container
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: domainresearch
      MYSQL_USER: jingb
      MYSQL_PASSWORD: domainresearch
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_volume:
